[global]
checkNewVersion = true
sendAnonymousUsage = false

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.web.http]
[entryPoints.web.http.redirections]
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"
permanent = true

[entryPoints.websecure]
address = ":443"

[log]
level = "info"

[api]
dashboard = true
insecure = false

[ping]

[providers]
[providers.docker]
exposedByDefault = false

[providers.file]
directory = "/etc/traefik/configs"
watch = true
