[[tls.certificates]]
certFile = "/etc/ssl/phpcon-dev.pl.crt"
keyFile = "/etc/ssl/phpcon-dev.pl.key"
stores = ["default"]

[tls.stores]
[tls.stores.default]
[tls.stores.default.defaultCertificate]
certFile = "/etc/ssl/phpcon-dev.pl.crt"
keyFile = "/etc/ssl/phpcon-dev.pl.key"
